apiVersion: batch/v1
kind: Job
metadata:
  name: iot-producer-job-5
  namespace: kafka
spec:
  completions: 5
  parallelism: 5
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: producer
        image: 192.168.5.107:5000/iot-producer:latest
        command: ["/bin/sh", "-c"]
        args: ["python3 producer.py && sleep 1h"]
        env:
        - name: KAFKA_BROKER
          value: "kafka-service.kafka.svc.cluster.local:9092"
        - name: PUBLISH_TOPIC
          value: "team21"
        - name: INFERENCE_TOPIC
          value: "inference_result"
        - name: TOTAL_SAMPLES
          value: "1000"
        - name: SAMPLE_FREQUENCY
          value: "1"
        - name: PRODUCER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: results
          mountPath: /results
      volumes:
      - name: results
        hostPath:
          path: /opt/producer-results
          type: DirectoryOrCreate
      restartPolicy: Never
