apiVersion: v1
kind: Pod
metadata:
  name: results-retriever
  namespace: kafka
spec:
  containers:
  - name: retriever
    image: 192.168.5.107:5000/iot-producer:latest  # Using same image for compatibility
    command: ['sleep', '3600']
    volumeMounts:
    - name: results
      mountPath: /app/results
  volumes:
  - name: results
    hostPath:
      path: /opt/producer-results
      type: DirectoryOrCreate
