---
- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Configure containerd
  copy:
    dest: /etc/containerd/config.toml
    content: |
      version = 2
      root = "/var/lib/containerd"
      state = "/run/containerd"

      [grpc]
        address = "/run/containerd/containerd.sock"
        
      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
          sandbox_image = "registry.k8s.io/pause:3.8"
          [plugins."io.containerd.grpc.v1.cri".containerd]
            default_runtime_name = "runc"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                runtime_type = "io.containerd.runc.v2"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true
          [plugins."io.containerd.grpc.v1.cri".registry]
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
              [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{ hostvars['Team21_vm1'].ansible_host }}:5000"]
                endpoint = ["http://{{ hostvars['Team21_vm1'].ansible_host }}:5000"]

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes
